/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Cliente;
import Modelo.ClienteDao;
import Modelo.Productos;
import Modelo.ProductosDao;
import Modelo.Proveedor;
import Modelo.ProveedorDao;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author ashle
 */
 public class Sistema extends javax.swing.JFrame {
Cliente cl = new Cliente();
ClienteDao client = new ClienteDao();
Proveedor pr = new Proveedor();
ProveedorDao PrDao = new ProveedorDao();
Productos pro = new Productos();
ProductosDao ProDao = new ProductosDao();
DefaultTableModel modelo = new DefaultTableModel();
int item;
double Totalpagar = 0.00;

    public Sistema() {
        initComponents();
        this.setLocationRelativeTo(null);
      ProDao.ConsultarProveedor(txt_proveedor_producto);
      AutoCompleteDecorator.decorate(txt_proveedor_producto);
      ProDao.ConsultarProveedor(txt_proveedor_producto);
    }
public void ListarCliente(){
    List<Cliente> ListarCl = client.ListarCliente();
    modelo = (DefaultTableModel) TABLA_CLIENTE.getModel();
    Object[] ob = new Object [6];
    for(int i = 0; i < ListarCl.size(); i++){
        ob [0] = ListarCl.get(i).getId();
        ob [1] = ListarCl.get(i).getNombre();
        ob [2] = ListarCl.get(i).getTelefono();
        ob [3] = ListarCl.get(i).getDireccion();
        ob [4] = ListarCl.get(i).getNit();
        modelo.addRow(ob);
    }
    TABLA_CLIENTE.setModel(modelo);
}

public void ListarProveedor(){
    List<Proveedor> ListarPr = PrDao.ListarProveedor();
    modelo = (DefaultTableModel) TablaProveedor.getModel();
    Object[] ob = new Object [6];
    for(int i = 0; i < ListarPr.size(); i++){
        ob [0] = ListarPr.get(i).getId();
        ob [1] = ListarPr.get(i).getNombre();
        ob [2] = ListarPr.get(i).getTelefono();
        ob [3] = ListarPr.get(i).getDireccion();
        ob [4] = ListarPr.get(i).getDescripcion();
        modelo.addRow(ob);
    }
    TablaProveedor.setModel(modelo);
}

public void ListarProducto(){
    List<Productos> ListarPro = ProDao.ListarProductos();
    modelo = (DefaultTableModel) TablaProductos.getModel();
    Object[] ob = new Object [7];
    for(int i = 0; i < ListarPro.size(); i++){
        ob [0] = ListarPro.get(i).getId();
        ob [1] = ListarPro.get(i).getCodigo();
        ob [2] = ListarPro.get(i).getNombre();
        ob [3] = ListarPro.get(i).getDescripcion();
        ob [4] = ListarPro.get(i).getStock();
        ob [5] = ListarPro.get(i).getPrecio();
        ob [6] = ListarPro.get(i).getProveedor();
        modelo.addRow(ob);
    }
    TablaProductos.setModel(modelo);
}


public void LimpiarTabla(){
   for(int i = 0; i < modelo.getRowCount() ; i++){
       modelo.removeRow(i);
       i = i-1;
   }
}

/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Venta_panel = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_eliminar_venta = new javax.swing.JButton();
        txt_codigo_venta = new javax.swing.JTextField();
        txt_Descrip_venta = new javax.swing.JTextField();
        txt_cant_venta = new javax.swing.JTextField();
        txt_precio_venta = new javax.swing.JTextField();
        txt_stock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVenta = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txt_id_producto_venta = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btn_guardar_cliente = new javax.swing.JButton();
        btn_actualizar_cliente = new javax.swing.JButton();
        btn_eliminar_cliente = new javax.swing.JButton();
        btn_nuevo_cliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TABLA_CLIENTE = new javax.swing.JTable();
        txt_nit_cliente = new javax.swing.JTextField();
        txt_dire_cliente = new javax.swing.JTextField();
        txt_tele_cliente = new javax.swing.JTextField();
        txt_nombre_cliente = new javax.swing.JTextField();
        txt_codigo_cliente = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Descripción = new javax.swing.JLabel();
        btn_guardar_proveedor = new javax.swing.JButton();
        btn_actualizar_proveedor = new javax.swing.JButton();
        btn_eliminar_proveedor = new javax.swing.JButton();
        btn_nuevo_proveedor = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaProveedor = new javax.swing.JTable();
        txt_descri_proveedor = new javax.swing.JTextField();
        txt_dire_proveedor = new javax.swing.JTextField();
        txt_tele_proveedor = new javax.swing.JTextField();
        txt_nombre_proveedor = new javax.swing.JTextField();
        txt_id_proveedor = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btn_guardar_producto = new javax.swing.JButton();
        btn_actualizar_producto = new javax.swing.JButton();
        btn_eliminar_producto = new javax.swing.JButton();
        btn_nuevo_producto = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        txt_id_producto = new javax.swing.JTextField();
        txt_cant_producto = new javax.swing.JTextField();
        txt_descri_productos = new javax.swing.JTextField();
        txt_nombre_producto = new javax.swing.JTextField();
        txt_codigo_producto = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txt_proveedor_producto = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        txt_precio_producto = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaVentas = new javax.swing.JTable();
        btn_pdf = new javax.swing.JButton();
        label_id_ventas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombrecli_venta = new javax.swing.JTextField();
        txt_id_venta = new javax.swing.JTextField();
        btn_imprimir_venta = new javax.swing.JButton();
        labeltotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(179, 123, 67));

        jButton1.setText("CLIENTES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("PROVEEDORES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("VENTAS");

        jButton4.setText("PRODUCTOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("CONFIG");

        jButton6.setText("NUEVA VENTA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/descuento.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 650));

        Venta_panel.setOpaque(true);

        jLabel4.setText("CODIGO");

        jLabel5.setText("DESCRIPCIÓN");

        jLabel6.setText("CANTIDAD");

        jLabel7.setText("PRECIO");

        jLabel8.setText("STOCK");

        btn_eliminar_venta.setText("ELIMINAR");
        btn_eliminar_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_ventaActionPerformed(evt);
            }
        });

        txt_codigo_venta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigo_ventaKeyPressed(evt);
            }
        });

        txt_cant_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cant_ventaActionPerformed(evt);
            }
        });
        txt_cant_venta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cant_ventaKeyPressed(evt);
            }
        });

        txt_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stockActionPerformed(evt);
            }
        });

        TablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(TablaVenta);
        if (TablaVenta.getColumnModel().getColumnCount() > 0) {
            TablaVenta.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaVenta.getColumnModel().getColumn(1).setPreferredWidth(30);
            TablaVenta.getColumnModel().getColumn(2).setPreferredWidth(30);
            TablaVenta.getColumnModel().getColumn(3).setPreferredWidth(30);
            TablaVenta.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        jLabel13.setText("ID PRODUCTO");

        txt_id_producto_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_producto_ventaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txt_codigo_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txt_Descrip_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_cant_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txt_precio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id_producto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btn_eliminar_venta)
                        .addGap(31, 31, 31))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_codigo_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Descrip_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cant_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_precio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id_producto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btn_eliminar_venta)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Venta_panel.addTab("VENTA", jPanel8);

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel19.setText("ID CLIENTE");

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel20.setText("Nombre");

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel21.setText("TELEFONO");

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel22.setText("DIRECCIÓN");

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel23.setText("NIT");

        btn_guardar_cliente.setText("GUARDAR");
        btn_guardar_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_guardar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_clienteActionPerformed(evt);
            }
        });

        btn_actualizar_cliente.setText("ACTUALIZAR");
        btn_actualizar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_clienteActionPerformed(evt);
            }
        });

        btn_eliminar_cliente.setText("ELIMINAR");
        btn_eliminar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_clienteActionPerformed(evt);
            }
        });

        btn_nuevo_cliente.setText("NUEVO");
        btn_nuevo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo_clienteActionPerformed(evt);
            }
        });

        TABLA_CLIENTE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "TELEFONO", "DIRECCION", "NIT"
            }
        ));
        TABLA_CLIENTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLA_CLIENTEMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TABLA_CLIENTE);
        if (TABLA_CLIENTE.getColumnModel().getColumnCount() > 0) {
            TABLA_CLIENTE.getColumnModel().getColumn(0).setPreferredWidth(30);
            TABLA_CLIENTE.getColumnModel().getColumn(1).setPreferredWidth(30);
            TABLA_CLIENTE.getColumnModel().getColumn(2).setPreferredWidth(30);
            TABLA_CLIENTE.getColumnModel().getColumn(3).setPreferredWidth(30);
            TABLA_CLIENTE.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        txt_tele_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tele_clienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_guardar_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_actualizar_cliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_eliminar_cliente)
                        .addGap(18, 18, 18)
                        .addComponent(btn_nuevo_cliente))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_codigo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_dire_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nit_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tele_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txt_codigo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_tele_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_dire_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nit_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar_cliente)
                    .addComponent(btn_actualizar_cliente)
                    .addComponent(btn_eliminar_cliente)
                    .addComponent(btn_nuevo_cliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        Venta_panel.addTab("CLIENTES", jPanel4);

        jLabel24.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel24.setText("ID PROVEEDOR");

        jLabel25.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel25.setText("Nombre");

        jLabel26.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel26.setText("TELEFONO");

        jLabel27.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel27.setText("DIRECCIÓN");

        Descripción.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Descripción.setText("Descripción");

        btn_guardar_proveedor.setText("GUARDAR");
        btn_guardar_proveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_guardar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_proveedorActionPerformed(evt);
            }
        });

        btn_actualizar_proveedor.setText("ACTUALIZAR");
        btn_actualizar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_proveedorActionPerformed(evt);
            }
        });

        btn_eliminar_proveedor.setText("ELIMINAR");
        btn_eliminar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_proveedorActionPerformed(evt);
            }
        });

        btn_nuevo_proveedor.setText("NUEVO");
        btn_nuevo_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevo_proveedorActionPerformed(evt);
            }
        });

        TablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "TELEFONO", "DIRECCION", "DESCRIPCION"
            }
        ));
        TablaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProveedorMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaProveedor);
        if (TablaProveedor.getColumnModel().getColumnCount() > 0) {
            TablaProveedor.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaProveedor.getColumnModel().getColumn(1).setPreferredWidth(30);
            TablaProveedor.getColumnModel().getColumn(2).setPreferredWidth(30);
            TablaProveedor.getColumnModel().getColumn(3).setPreferredWidth(30);
            TablaProveedor.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        txt_tele_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tele_proveedorActionPerformed(evt);
            }
        });

        txt_id_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_proveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(Descripción)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_id_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_guardar_proveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_actualizar_proveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_dire_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_descri_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tele_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btn_eliminar_proveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_nuevo_proveedor)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txt_id_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txt_nombre_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_tele_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txt_dire_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_descri_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descripción))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar_proveedor)
                    .addComponent(btn_actualizar_proveedor)
                    .addComponent(btn_eliminar_proveedor)
                    .addComponent(btn_nuevo_proveedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        Venta_panel.addTab("PROVEEDORES", jPanel5);

        jLabel29.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel29.setText("CODIGO");

        jLabel30.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel30.setText("Nombre");

        jLabel31.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel31.setText("DESCRIPCION");

        jLabel32.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel32.setText("STOCK");

        jLabel33.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel33.setText("PRECIO");

        btn_guardar_producto.setText("GUARDAR");
        btn_guardar_producto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_guardar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_productoActionPerformed(evt);
            }
        });

        btn_actualizar_producto.setText("ACTUALIZAR");
        btn_actualizar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizar_productoActionPerformed(evt);
            }
        });

        btn_eliminar_producto.setText("ELIMINAR");
        btn_eliminar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_productoActionPerformed(evt);
            }
        });

        btn_nuevo_producto.setText("NUEVO");

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CODIGO", "NOMBRE", "DESCRIPCIÓN", "STOCK", "PRECIO", "PROVEEDOR"
            }
        ));
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TablaProductos);
        if (TablaProductos.getColumnModel().getColumnCount() > 0) {
            TablaProductos.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaProductos.getColumnModel().getColumn(1).setPreferredWidth(30);
            TablaProductos.getColumnModel().getColumn(2).setPreferredWidth(30);
            TablaProductos.getColumnModel().getColumn(3).setPreferredWidth(30);
            TablaProductos.getColumnModel().getColumn(4).setPreferredWidth(30);
            TablaProductos.getColumnModel().getColumn(5).setPreferredWidth(30);
            TablaProductos.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        txt_descri_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descri_productosActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel40.setText("ID");

        txt_proveedor_producto.setEditable(true);
        txt_proveedor_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_proveedor_productoActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel41.setText("PROVEEDOR");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btn_guardar_producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_actualizar_producto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_eliminar_producto)
                        .addGap(18, 18, 18)
                        .addComponent(btn_nuevo_producto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_proveedor_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel32)
                                .addComponent(jLabel33)
                                .addComponent(jLabel31)
                                .addComponent(jLabel30)
                                .addComponent(jLabel29)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_codigo_producto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre_producto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_descri_productos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cant_producto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(212, 212, 212)
                    .addComponent(txt_precio_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(458, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txt_codigo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txt_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txt_descri_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(txt_cant_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_proveedor_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(txt_id_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_guardar_producto)
                            .addComponent(btn_actualizar_producto)
                            .addComponent(btn_eliminar_producto)
                            .addComponent(btn_nuevo_producto)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(159, 159, 159)
                    .addComponent(txt_precio_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(243, Short.MAX_VALUE)))
        );

        Venta_panel.addTab("PRODUCTOS", jPanel6);

        TablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CLIENTE", "VENDEDOR", "TOTAL"
            }
        ));
        jScrollPane6.setViewportView(TablaVentas);
        if (TablaVentas.getColumnModel().getColumnCount() > 0) {
            TablaVentas.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaVentas.getColumnModel().getColumn(1).setPreferredWidth(30);
            TablaVentas.getColumnModel().getColumn(2).setPreferredWidth(30);
            TablaVentas.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        btn_pdf.setText("PDF");

        label_id_ventas.setText("ID");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label_id_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_pdf)
                .addGap(57, 57, 57))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pdf)
                    .addComponent(label_id_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 95, Short.MAX_VALUE))
        );

        Venta_panel.addTab("VENTAS", jPanel7);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel14.setText("Nombre");

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel15.setText("ID");

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel16.setText("TELEFONO");

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel17.setText("RAZON SOCIAL");

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel18.setText("DIRECCIÓN");

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(212, 146, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/carrito-de-supermercado.png"))); // NOI18N

        jLabel34.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("DATOS DE LA EMPRESA");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jButton9.setBackground(new java.awt.Color(162, 101, 60));
        jButton9.setText("ACTUALIZAR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(68, 68, 68)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        Venta_panel.addTab("CONFIGURACIÓN", jPanel3);

        getContentPane().add(Venta_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 840, 450));

        jPanel2.setBackground(new java.awt.Color(179, 123, 67));

        jLabel1.setFont(new java.awt.Font("Artifakt Element Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 221, 216));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CONEJO.png"))); // NOI18N
        jLabel1.setText("SUPERMERCADO EL \"FAST BUNNY\"");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 860, 90));
        getContentPane().add(txt_nombrecli_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 250, -1));

        txt_id_venta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_id_ventaKeyPressed(evt);
            }
        });
        getContentPane().add(txt_id_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 160, -1));

        btn_imprimir_venta.setText("IMPRIMIR");
        btn_imprimir_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimir_ventaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_imprimir_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 570, 120, 50));

        labeltotal.setBackground(new java.awt.Color(153, 102, 0));
        labeltotal.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        labeltotal.setForeground(new java.awt.Color(243, 230, 217));
        labeltotal.setText("...");
        labeltotal.setOpaque(true);
        getContentPane().add(labeltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 600, 170, 30));

        jLabel12.setBackground(new java.awt.Color(153, 102, 0));
        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(243, 230, 217));
        jLabel12.setText("TOTAL A PAGAR");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 170, 30));

        jLabel11.setBackground(new java.awt.Color(153, 102, 0));
        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(243, 230, 217));
        jLabel11.setText("NOMBRE");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 100, 30));

        jLabel10.setBackground(new java.awt.Color(153, 102, 0));
        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(243, 230, 217));
        jLabel10.setText("ID");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/FONDO 2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 4, 870, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt_cant_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cant_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cant_ventaActionPerformed

    private void txt_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stockActionPerformed

    private void btn_imprimir_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimir_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimir_ventaActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void txt_tele_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tele_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tele_clienteActionPerformed

    private void txt_tele_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tele_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tele_proveedorActionPerformed

    private void txt_id_producto_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_producto_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_producto_ventaActionPerformed

    private void btn_guardar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_clienteActionPerformed
        // TODO add your handling code here:
        
        if(! "".equals(txt_nombre_cliente.getText()) || !"".equals(txt_tele_cliente.getText()) || !"".equals(txt_dire_cliente.getText()) || !"".equals(txt_nit_cliente.getText())){
           
            cl.setNombre(txt_nombre_cliente.getText());
            cl.setTelefono(Integer.parseInt(txt_tele_cliente.getText()));
            cl.setDireccion(txt_dire_cliente.getText());
            cl.setNit((txt_nit_cliente.getText()));
            client.RegistrarCliente(cl);
            LimpiarTabla();
            LimpiarCliente();        
            ListarCliente();
            JOptionPane.showMessageDialog(null,"CLIENTE REGISTRADO :D" );
        }else{
             JOptionPane.showMessageDialog(null,"LOS CAMPOS ESTAN VACIOS, PENDEJO >:V " );
        }
    }//GEN-LAST:event_btn_guardar_clienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        ListarCliente();
        Venta_panel.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TABLA_CLIENTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLA_CLIENTEMouseClicked
        // TODO add your handling code here:
     int fila = TABLA_CLIENTE.rowAtPoint(evt.getPoint());
     txt_codigo_cliente.setText(TABLA_CLIENTE.getValueAt(fila,0).toString());
     txt_nombre_cliente.setText(TABLA_CLIENTE.getValueAt(fila,1).toString());
     txt_tele_cliente.setText(TABLA_CLIENTE.getValueAt(fila,2).toString());
     txt_dire_cliente.setText(TABLA_CLIENTE.getValueAt(fila,3).toString());
     txt_nit_cliente.setText(TABLA_CLIENTE.getValueAt(fila,4).toString());    
        
    }//GEN-LAST:event_TABLA_CLIENTEMouseClicked

    private void btn_eliminar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_clienteActionPerformed
        // TODO add your handling code here:
        if(! "".equals(txt_codigo_cliente.getText())){
            int  pregunta = JOptionPane.showConfirmDialog(null, "SEGURO QUIERES ELIMINAR EL CLIENTE? ");
            if (pregunta == 0 ){
                int id = Integer.parseInt(txt_codigo_cliente.getText());
                client.EliminarCliente(id);
                LimpiarTabla();
                LimpiarCliente();
                ListarCliente();
            }
                    
        }
        
    }//GEN-LAST:event_btn_eliminar_clienteActionPerformed

    private void btn_actualizar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_clienteActionPerformed
        // TODO add your handling code here:
        
        if("".equals(txt_codigo_cliente.getText())){
            JOptionPane.showMessageDialog(null,"SELECCIONA UNA FILA ;v" );
        }else{
         
           if (!"".equals(txt_nombre_cliente.getText()) || !"".equals(txt_tele_cliente.getText()) || !"".equals(txt_dire_cliente.getText()) || !"".equals(txt_nit_cliente.getText())){
               
            cl.setNombre(txt_nombre_cliente.getText());
            cl.setTelefono(Integer.parseInt(txt_tele_cliente.getText()));
            cl.setDireccion(txt_dire_cliente.getText());
            cl.setNit(txt_nit_cliente.getText());
            cl.setId(Integer.parseInt(txt_codigo_cliente.getText()));
               
               client.ModificarCliente(cl);
                LimpiarTabla();
                LimpiarCliente();
                ListarCliente();
           } else{
             JOptionPane.showMessageDialog(null,"LOS CAMPOS ESTAN VACIOS PENDEJO >:V " );  
           }
        }
    }//GEN-LAST:event_btn_actualizar_clienteActionPerformed

    private void btn_nuevo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo_clienteActionPerformed
        // TODO add your handling code here:
       
         LimpiarCliente();
     
    }//GEN-LAST:event_btn_nuevo_clienteActionPerformed

    private void btn_guardar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_proveedorActionPerformed
        // TODO add your handling code here:
        
        if(! "".equals(txt_nombre_proveedor.getText()) || !"".equals(txt_tele_proveedor.getText()) || !"".equals(txt_dire_proveedor.getText()) || !"".equals(txt_descri_proveedor.getText())){
           
            pr.setNombre(txt_nombre_proveedor.getText());
            pr.setTelefono(Integer.parseInt(txt_tele_proveedor.getText()));
            pr.setDireccion(txt_dire_proveedor.getText());
            pr.setDescripcion((txt_descri_proveedor.getText()));
            PrDao.RegistrarProveedor(pr);
            LimpiarTabla();
            LimpiarProveedor();        
            ListarProveedor();
            JOptionPane.showMessageDialog(null,"PROVEEDOR REGISTRADO :D" );
        }else{
             JOptionPane.showMessageDialog(null,"LOS CAMPOS ESTAN VACIOS, PENDEJO >:V " );
        }
    }//GEN-LAST:event_btn_guardar_proveedorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
     
         ListarProveedor();
        Venta_panel.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TablaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProveedorMouseClicked
        // TODO add your handling code here:
      int fila = TablaProveedor.rowAtPoint(evt.getPoint());
     txt_id_proveedor.setText(TablaProveedor.getValueAt(fila,0).toString());
     txt_nombre_proveedor.setText(TablaProveedor.getValueAt(fila,1).toString());
     txt_tele_proveedor.setText(TablaProveedor.getValueAt(fila,2).toString());
     txt_dire_proveedor.setText(TablaProveedor.getValueAt(fila,3).toString());
     txt_descri_proveedor.setText(TablaProveedor.getValueAt(fila,4).toString()); 
    }//GEN-LAST:event_TablaProveedorMouseClicked

    private void btn_eliminar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_proveedorActionPerformed
        // TODO add your handling code here:
   if(! "".equals(txt_id_proveedor.getText())){
            int  pregunta = JOptionPane.showConfirmDialog(null, "SEGURO QUIERES ELIMINAR EL PROVEEDOR? ");
            if (pregunta == 0 ){
                int id = Integer.parseInt(txt_id_proveedor.getText());
                PrDao.EliminarProveedor(id);
                LimpiarTabla();
                ListarProveedor();
                LimpiarProveedor();
            }
                    
        }else{
        JOptionPane.showMessageDialog(null,"SELECCIONA UNA FILA ;v" );
   }
    }//GEN-LAST:event_btn_eliminar_proveedorActionPerformed

    private void btn_actualizar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_proveedorActionPerformed
        // TODO add your handling code here:
         if("".equals(txt_id_proveedor.getText())){
            JOptionPane.showMessageDialog(null,"SELECCIONA UNA FILA ;v" );
        }else{
         
           if (!"".equals(txt_nombre_proveedor.getText()) || !"".equals(txt_tele_proveedor.getText()) || !"".equals(txt_dire_proveedor.getText()) || !"".equals(txt_descri_proveedor.getText())){
               
            pr.setNombre(txt_nombre_proveedor.getText());
            pr.setTelefono(Integer.parseInt(txt_tele_proveedor.getText()));
            pr.setDireccion(txt_dire_proveedor.getText());
            pr.setDescripcion(txt_descri_proveedor.getText());
            pr.setId(Integer.parseInt(txt_id_proveedor.getText()));
               
               PrDao.ModificarProveedor(pr);
                JOptionPane.showMessageDialog(null,"PROVEEDOR MODIFICADO ;v" );
                LimpiarTabla();
                LimpiarProveedor();
                ListarProveedor();
           } else{
             JOptionPane.showMessageDialog(null,"LOS CAMPOS ESTAN VACIOS PENDEJO >:V " );  
           }
        }
    }//GEN-LAST:event_btn_actualizar_proveedorActionPerformed

    private void txt_id_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_proveedorActionPerformed

    private void btn_nuevo_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevo_proveedorActionPerformed
        // TODO add your handling code here:
         LimpiarProveedor();
    }//GEN-LAST:event_btn_nuevo_proveedorActionPerformed

    private void txt_descri_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descri_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descri_productosActionPerformed

    private void btn_guardar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_productoActionPerformed
        // TODO add your handling code here:
        if(! "".equals(txt_codigo_producto.getText()) || !"".equals(txt_nombre_producto.getText()) || !"".equals(txt_descri_productos.getText()) || !"".equals(txt_cant_producto.getText())|| !"".equals(txt_precio_producto.getText())|| !"".equals(txt_proveedor_producto.getSelectedItem())){
            
            pro.setCodigo(txt_codigo_producto.getText());
            pro.setNombre(txt_nombre_producto.getText());
            pro.setDescripcion(txt_descri_productos.getText());
            pro.setPrecio(Double.parseDouble(txt_precio_producto.getText()));
            pro.setStock(Integer.parseInt(txt_cant_producto.getText()));
            pro.setProveedor(txt_proveedor_producto.getSelectedItem().toString());
            ProDao.RegistrarProductos(pro);
            // LimpiarTabla();
            // LimpiarProducto();
            //ListarProducto();
            JOptionPane.showMessageDialog(null,"PRODUCTO REGISTRADO :D" );
        }else{
            JOptionPane.showMessageDialog(null,"LOS CAMPOS ESTAN VACIOS, PENDEJO >:V " );
        }
    }//GEN-LAST:event_btn_guardar_productoActionPerformed

    private void txt_proveedor_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_proveedor_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_proveedor_productoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        LimpiarTabla();
        ListarProducto();
        Venta_panel.setSelectedIndex(3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked
        // TODO add your handling code here:
         int fila = TablaProductos.rowAtPoint(evt.getPoint());
     txt_id_producto.setText(TablaProductos.getValueAt(fila,0).toString());
     txt_codigo_producto.setText(TablaProductos.getValueAt(fila,1).toString());
     txt_nombre_producto.setText(TablaProductos.getValueAt(fila,2).toString());
     txt_descri_productos.setText(TablaProductos.getValueAt(fila,3).toString());
     txt_cant_producto.setText(TablaProductos.getValueAt(fila,4).toString());
     txt_precio_producto.setText(TablaProductos.getValueAt(fila,5).toString());
     txt_proveedor_producto.setSelectedItem(TablaProductos.getValueAt(fila,6).toString());
    }//GEN-LAST:event_TablaProductosMouseClicked

    private void btn_eliminar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_productoActionPerformed
        // TODO add your handling code here:
         if(! "".equals(txt_id_producto.getText())){
            int  pregunta = JOptionPane.showConfirmDialog(null, "SEGURO QUIERES ELIMINAR EL PRODUCTO? ");
            if (pregunta == 0 ){
                int id = Integer.parseInt(txt_id_producto.getText());
                ProDao.EliminarProductos(id);
                LimpiarTabla();
                LimpiarProductos();
                ListarProducto();
            }
                    
        }
    }//GEN-LAST:event_btn_eliminar_productoActionPerformed

    private void btn_actualizar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizar_productoActionPerformed
        // TODO add your handling code here:
      if("".equals(txt_id_producto.getText())){
            JOptionPane.showMessageDialog(null,"SELECCIONA UNA FILA ;v" );
        }else{
         
           if (!"".equals(txt_codigo_producto.getText()) || !"".equals(txt_nombre_producto.getText()) || !"".equals(txt_descri_productos.getText()) || !"".equals(txt_cant_producto.getText()) || !"".equals(txt_precio_producto.getText())){
               
            pro.setCodigo(txt_codigo_producto.getText());
            pro.setNombre(txt_nombre_producto.getText());
            pro.setDescripcion(txt_descri_productos.getText());
            pro.setStock(Integer.parseInt(txt_cant_producto.getText()));
            pro.setPrecio(Double.parseDouble(txt_precio_producto.getText()));
            pro.setProveedor(txt_proveedor_producto.getSelectedItem().toString());
               
               ProDao.ModificarProductos(pro);
                LimpiarTabla();
                LimpiarProductos();
                ListarProducto();
           } else{
             JOptionPane.showMessageDialog(null,"LOS CAMPOS ESTAN VACIOS PENDEJO >:V " );  
           }
        }
    }//GEN-LAST:event_btn_actualizar_productoActionPerformed

    private void txt_codigo_ventaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigo_ventaKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          if(!"".equals(txt_codigo_venta.getText())){
              String cod=txt_codigo_venta.getText();
              pro=ProDao.BuscarPro(cod);
              if(pro.getNombre() !=null){
                  txt_Descrip_venta.setText(""+pro.getNombre());
                  txt_precio_venta.setText(""+pro.getPrecio());
                  txt_stock.setText(""+pro.getStock());
                  txt_cant_venta.requestFocus();
                  
              }else{
                  LimpiarVenta();
                  
                 txt_codigo_venta.requestFocus();   
              }
          }else{
              JOptionPane.showMessageDialog(null,"INGRESE EL CODIGO DEL PRODUCTO " );
              txt_codigo_venta.requestFocus(); 
          }  
        }
    }//GEN-LAST:event_txt_codigo_ventaKeyPressed

    private void txt_cant_ventaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cant_ventaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!"".equals(txt_cant_venta.getText())){
                String cod = txt_codigo_venta.getText();
                String descripcion = txt_Descrip_venta.getText();
                int cant = Integer.parseInt(txt_cant_venta.getText());
                double precio = Double.parseDouble(txt_precio_venta.getText());
                double total = cant * precio;
                int stock = Integer.parseInt(txt_stock.getText());
                if(stock >= cant){
                    item = item + 1;
                    modelo = (DefaultTableModel) TablaVenta.getModel();
                    for(int i = 0; i< TablaVenta.getRowCount(); i++){
                        if(TablaVenta.getValueAt(i, 1).equals(txt_Descrip_venta.getText())){
                          JOptionPane.showMessageDialog(null,"EL PRODUCTO YA ESTA REGISTRADO" );   
                          return;
                        }
                        
                    }
                    ArrayList lista = new ArrayList();
                    lista.add(item);
                    lista.add(cod);
                    lista.add(descripcion);
                    lista.add(cant);
                    lista.add(precio);
                    lista.add(total);
                    Object[] O = new Object[5];
                    O[0] = lista.get(1);
                    O[1] = lista.get(2);
                    O[2] = lista.get(3);        
                    O[3] = lista.get(4);
                    O[4] = lista.get(5);
                    modelo.addRow(O);
                    TablaVenta.setModel(modelo);
                    TotalPagar();
                    LimpiarVenta();
                    txt_codigo_venta.requestFocus();
                }else{
                    JOptionPane.showMessageDialog(null,"STOCK NO DISPONIBLE :( " ); 
                }
            }else{
               JOptionPane.showMessageDialog(null,"INGRESE CANTIDAD  " ); 
            }
        }
    }//GEN-LAST:event_txt_cant_ventaKeyPressed

    private void btn_eliminar_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_ventaActionPerformed
        // TODO add your handling code here:
        modelo = (DefaultTableModel) TablaVenta.getModel();
        modelo.removeRow(TablaVenta.getSelectedRow());
        TotalPagar();
        txt_codigo_venta.requestFocus();
    }//GEN-LAST:event_btn_eliminar_ventaActionPerformed

    private void txt_id_ventaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_ventaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!"".equals(txt_id_venta.getText())){
                int id = Integer.parseInt(txt_id_venta.getText());
                cl = client.Buscarcliente(id);
               
                if(cl.getNombre() != null){
                    txt_nombrecli_venta.setText(""+cl.getNombre());
                   
            }else{
                    txt_id_venta.setText("");
                JOptionPane.showMessageDialog(null,"EL CLIENTE NO EXISTE" );      
                    }      
    }//GEN-LAST:event_txt_id_ventaKeyPressed
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripción;
    private javax.swing.JTable TABLA_CLIENTE;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTable TablaProveedor;
    private javax.swing.JTable TablaVenta;
    private javax.swing.JTable TablaVentas;
    private javax.swing.JTabbedPane Venta_panel;
    private javax.swing.JButton btn_actualizar_cliente;
    private javax.swing.JButton btn_actualizar_producto;
    private javax.swing.JButton btn_actualizar_proveedor;
    private javax.swing.JButton btn_eliminar_cliente;
    private javax.swing.JButton btn_eliminar_producto;
    private javax.swing.JButton btn_eliminar_proveedor;
    private javax.swing.JButton btn_eliminar_venta;
    private javax.swing.JButton btn_guardar_cliente;
    private javax.swing.JButton btn_guardar_producto;
    private javax.swing.JButton btn_guardar_proveedor;
    private javax.swing.JButton btn_imprimir_venta;
    private javax.swing.JButton btn_nuevo_cliente;
    private javax.swing.JButton btn_nuevo_producto;
    private javax.swing.JButton btn_nuevo_proveedor;
    private javax.swing.JButton btn_pdf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel label_id_ventas;
    private javax.swing.JLabel labeltotal;
    private javax.swing.JTextField txt_Descrip_venta;
    private javax.swing.JTextField txt_cant_producto;
    private javax.swing.JTextField txt_cant_venta;
    private javax.swing.JTextField txt_codigo_cliente;
    private javax.swing.JTextField txt_codigo_producto;
    private javax.swing.JTextField txt_codigo_venta;
    private javax.swing.JTextField txt_descri_productos;
    private javax.swing.JTextField txt_descri_proveedor;
    private javax.swing.JTextField txt_dire_cliente;
    private javax.swing.JTextField txt_dire_proveedor;
    private javax.swing.JTextField txt_id_producto;
    private javax.swing.JTextField txt_id_producto_venta;
    private javax.swing.JTextField txt_id_proveedor;
    private javax.swing.JTextField txt_id_venta;
    private javax.swing.JTextField txt_nit_cliente;
    private javax.swing.JTextField txt_nombre_cliente;
    private javax.swing.JTextField txt_nombre_producto;
    private javax.swing.JTextField txt_nombre_proveedor;
    private javax.swing.JTextField txt_nombrecli_venta;
    private javax.swing.JTextField txt_precio_producto;
    private javax.swing.JTextField txt_precio_venta;
    private javax.swing.JComboBox<String> txt_proveedor_producto;
    private javax.swing.JTextField txt_stock;
    private javax.swing.JTextField txt_tele_cliente;
    private javax.swing.JTextField txt_tele_proveedor;
    // End of variables declaration//GEN-END:variables
private void LimpiarCliente(){
    txt_codigo_cliente.setText("");
    txt_nombre_cliente.setText("");
    txt_tele_cliente.setText(""); 
    txt_dire_cliente.setText("");        
    txt_nit_cliente.setText("");        
}
private void LimpiarProveedor(){
    txt_id_proveedor.setText("");
    txt_nombre_proveedor.setText("");
    txt_tele_proveedor.setText(""); 
    txt_dire_proveedor.setText("");        
    txt_descri_proveedor.setText("");        
}
private void LimpiarProductos(){
    txt_id_producto.setText("");
    txt_codigo_producto.setText("");
    txt_nombre_producto.setText(""); 
    txt_descri_productos.setText("");        
    txt_cant_producto.setText(""); 
    txt_precio_producto.setText("");
    txt_proveedor_producto.setSelectedItem(null);
}
private void TotalPagar(){
Totalpagar = 0.00;
int numFila = TablaVenta.getRowCount();
 for (int i = 0; i < numFila; i++){
     double cal = Double.parseDouble(String.valueOf(TablaVenta.getModel().getValueAt(i,3)));
     Totalpagar = Totalpagar + cal;
     
 }   
labeltotal.setText(String.format("%.2f", Totalpagar));
}
private void LimpiarVenta(){
    
    txt_codigo_venta.setText("");
    txt_Descrip_venta.setText("");
    txt_cant_venta.setText("");
     txt_stock.setText("");
      txt_precio_venta.setText("");
}
    
 }




